import pandas as pd
import os
import matplotlib
import inspect
import matplotlib.pyplot as plt
import datetime
from tabulate import tabulate
from pathlib import Path


class Journalist():
    def __init__(self, template_file=None, fig_width=None, fig_height=None, floatfmt='.2f', tmp_path='./temp'):
        self.template_file = template_file
        self.report_config = {}
        self._width = fig_width
        self._height = fig_height
        self.var_type = {}
        self.fig_counters = 0
        self.floatfmt = floatfmt
        self.tmp_path = tmp_path
        if not os.path.exists(tmp_path):
            os.mkdir(tmp_path)
        if fig_width:
            self.fig_config = '{{ ' + f'width={fig_width}%' + ' }}'
        elif fig_height:
            self.fig_config = '{{ ' + f'height={fig_height}%' + ' }}'
        else:
            self.fig_config = ''

    def __preprocess(self, config_dict: dict):
        for k in config_dict:
            report_content = config_dict[k]
            if isinstance(report_content, pd.DataFrame):
                # transform into a string with markdown table format,
                config_dict[k] = tabulate(report_content, floatfmt=self.floatfmt, tablefmt='github',headers='keys')
                self.var_type[k] = 'table'

            elif isinstance(report_content, matplotlib.axes.SubplotBase):
                # save plot generated by matplotlib to a pdf format in temp directory
                fig_file = os.path.join(self.tmp_path, f'figure_{self.fig_counters}.pdf')
                self.fig_counters += 1
                ax = report_content.get_figure()
                ax.tight_layout = True
                ax.savefig(fig_file)
                config_dict[k] = fig_file
                self.var_type[k] = 'figure'

            elif callable(report_content):
                # print function definition on final report
                config_dict[k] = inspect.getsource(report_content)
                self.var_type[k] = 'function'

            elif isinstance(report_content, list) and all(isinstance(s, str) for s in report_content):
                # concatenate all words into a sentence
                config_dict[k] = str(len(report_content)) + ' ' + ', '.join(report_content)
                self.var_type[k] = 'list(str)'

            else:
                # otherwise: leave it as origin format (use its own str method)
                self.var_type[k] = 'other'

        return config_dict

    def hear(self, config_dict: dict):
        newest_config = self.__preprocess(config_dict)
        self.report_config.update(newest_config)

    def generate_template(self, template_file='./template.md'):
        if self.template_file:
            print('warning: template file was specified before and will be overwritten')
        self.template_file = template_file
        report_text = '# Report template \n\n'
        for k, v in self.var_type.items():
            k_name = '{' + k + '}'
            title = f"### {k}\n\n"
            if v == 'figure':
                content = f'![]({k_name}){self.fig_config}\n\n'
            elif v == 'function':
                title = f"### {k}" + '{{.fragile}}\n\n'
                content = '~~~{{.python}}\n' + v + '\n~~~\n\n'
            else:
                content = k_name + '\n\n'
            report_text = report_text + title + content

        Path(template_file).write_text(report_text)
        print(f'New template file is generated in {template_file}')

    def report(self, final_report_file='final_report', format='pdf', beamer=True, theme='default',
               color_theme='seagull', font_size='18pt',use_template_config=False):
        raw_file = os.path.join(self.tmp_path, 'raw_report.md')
        timestamp = datetime.datetime.now()
        final_file = f"{final_report_file}_{timestamp}{format}".replace(' ', '_')
        self.report_config['today'] = datetime.datetime.today().date()

        report_template_text = open(self.template_file, 'r').read()
        Path(raw_file).write_text(report_template_text.format(**self.report_config))
        if beamer and format == '.pdf':
            command = f'pandoc -t beamer {raw_file} -V theme:{theme} -V colortheme:{color_theme} -s -o {final_file}'
        else:
            command = f'pandoc -t {raw_file} fontsize:{font_size} -s -o {final_file}'
        return_code = os.system(command)
        if return_code == 0:
            print(f'Make a big news! The newest report is now in {final_file}')
            return final_file
        else:
            print(f'Report failed with code {return_code}, please check if params and path correct')
            return return_code
